### ISSUE TITLE
any plans for 8.x versions?

### ISSUE THREAD

**Issue by salsa2k** [RaySSharma/fvtt-encounter-builder#10]
Any plans to make it work for the new versions?

thanks

**Comment by darthbane72** [comment]
Request for update seconded. seems like the mod will pull the box up upon clicking the side icon, but not update with  the tokens when dragged. loved using the mod, so I hope we can have an update soon!

**Comment by cnutenor** [comment]
Your module is extremely useful, please update it! :) Thanks a lot!
