### ISSUE TITLE
Update to 9.x

### ISSUE THREAD

**Issue by Segm3nts** [RaySSharma/fvtt-encounter-builder#13]
Hello! Just checking in to see if there are any plans to update this module to higher versions, such as 9.x? This module is an absolute lifesaver and I would love to use it, there's just nothing else like it out there!

I have no experience in writing modules for Foundry VTT, but I'm happy to help out if it makes it easier!

**Comment by RaySSharma** [comment]
#12 added compatability for 9.x!
